services:
  postgres_db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "welbex", "-U", "welbex" ]
      timeout: 5s
      interval: 5s
      retries: 5
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - backend
  
  redis_db:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - backend

  web_app:
    build: ./
    ports:
     - "8000:80"
    depends_on:
      postgres_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost/api/health-check || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 30s
    networks:
      - backend
  
  worker:
    build:
      context: ./
    hostname: worker
    entrypoint: celery
    command: -A app.celery worker -l info -B
    depends_on:
      redis_db:
        condition: service_healthy
      web_app:
        condition: service_healthy
    networks:
      - backend


networks:
  backend:
    driver: bridge
    name: backend
